/** Inbound: client -> call-service */
export enum ClientEvent {
  JOIN_ROOM = 'joinRoom',
  LEAVE_ROOM = 'leaveRoom',
  CREATE_TRANSPORT = 'createTransport',
  CONNECT_TRANSPORT = 'connectTransport',
  PRODUCE = 'produce',
  CONSUME = 'consume',
  PAUSE_PRODUCER = 'pauseProducer',
  RESUME_PRODUCER = 'resumeProducer',
  CLOSE_PRODUCER = 'closeProducer',
  RESUME_CONSUMER = 'resumeConsumer',
  RESTART_ICE = 'restartIce',
  START_SCREEN_SHARE = 'startScreenShare',
  STOP_SCREEN_SHARE = 'stopScreenShare',
  RAISE_HAND = 'raiseHand',
  LOWER_HAND = 'lowerHand',
  /** Host/moderator lowering *someone else's* hand — distinct from LOWER_HAND (self). */
  LOWER_PARTICIPANT_HAND = 'lowerParticipantHand',
  INVITE_TO_SPEAK = 'inviteToSpeak',
  REACTION = 'reaction',
  CHAT_MESSAGE = 'chatMessage',
  MUTE = 'mute',
  REQUEST_UNMUTE = 'requestUnmute',
  KICK = 'kick',
  LOCK_MEETING = 'lockMeeting',
  UNLOCK_MEETING = 'unlockMeeting',
  END_MEETING = 'endMeeting',
  PROMOTE_MODERATOR = 'promoteModerator',
  DEMOTE_MODERATOR = 'demoteModerator',
  ADMIT_WAITING_PARTICIPANT = 'admitWaitingParticipant',
  REJECT_WAITING_PARTICIPANT = 'rejectWaitingParticipant',
  HEARTBEAT = 'heartbeat',
}

/** Outbound: call-service -> client(s) */
export enum ServerEvent {
  USER_JOINED = 'userJoined',
  USER_LEFT = 'userLeft',
  NEW_PRODUCER = 'newProducer',
  PRODUCER_CLOSED = 'producerClosed',
  VIDEO_ENABLED = 'videoEnabled',
  VIDEO_DISABLED = 'videoDisabled',
  AUDIO_MUTED = 'audioMuted',
  AUDIO_UNMUTED = 'audioUnmuted',
  UNMUTE_REQUESTED = 'unmuteRequested',
  HAND_RAISED = 'handRaised',
  HAND_LOWERED = 'handLowered',
  REACTION = 'reaction',
  CHAT_MESSAGE = 'chatMessage',
  SCREEN_SHARE_STARTED = 'screenShareStarted',
  SCREEN_SHARE_STOPPED = 'screenShareStopped',
  PARTICIPANT_REMOVED = 'participantRemoved',
  PARTICIPANT_ROLE_CHANGED = 'participantRoleChanged',
  MEETING_LOCKED = 'meetingLocked',
  MEETING_UNLOCKED = 'meetingUnlocked',
  MEETING_ENDED = 'meetingEnded',
  MEETING_STATE_UPDATED = 'meetingStateUpdated',
  WAITING_ROOM_JOINED = 'waitingRoomJoined',
  WAITING_ROOM_PARTICIPANT = 'waitingRoomParticipant',
  WAITING_ROOM_REJECTED = 'waitingRoomRejected',
  ADMITTED = 'admitted',
  ACTIVE_SPEAKER_CHANGED = 'activeSpeakerChanged',
  FORCE_MUTED = 'forceMuted',
  ERROR = 'errorEvent',
  HEARTBEAT_ACK = 'heartbeatAck',
}
